### PR TITLE
Migrating provider to Terraform Plugin SDK.

### PR DESCRIPTION
**Pull request by lazzurs**
Migrating the provider to the Terraform Plugin SDK using the migration
tool.

### CODE REVIEW

**Comment by aareet** [comment]
@svanharmelen apologies for the delay here - do you need this PR to be merged?

**Comment by svanharmelen** [comment]
I think we should ask @lazzurs as he opened the PR. I only approved it... I can merge it as well if needed, but I thought to let @lazzurs take care of that 😉

**Comment by aareet** [comment]
Fair enough 😊, @lazzurs please let us know if this is still valuable to be merged

**Comment by lazzurs** [comment]
Hey so I just signed the CLA and I will update the PR to relfect the latest versions but yes happy to have this merged.

**Comment by lazzurs** [comment]
Upgraded to the latest version of the plugin SDK and tests are still running. Ready to merge.

**Comment by lazzurs** [comment]
This is now very out of date and the migration was done. Closing to tidy up PRs.

**Pull request closed without merging**
